import = [
    "~/.config/alacritty/themes/themes/solarized_osaka.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "Fira Code"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Fira Code"

[font.offset]
x = 0
y = 0
